# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYH7o_yL6b9sSDPzikh3rws0VRDZtX5a
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install streamlit pdfplumber reportlab pyngrok
!mkdir vibe_planner
# %cd vibe_planner

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vibe_planner_app.py
# # 📘 Orkun Temeltaş - Haftalık Çalışma Planı Arayüzü (Colab uyumlu)
# # Tam işlevli sürüm (arama, logo, ZIP, çoklu öğrenci destekli)
# 
# import streamlit as st
# import os
# import pdfplumber
# import datetime
# import json
# import zipfile
# from io import BytesIO
# from reportlab.lib.pagesizes import A4
# from reportlab.lib.units import mm
# from reportlab.pdfgen import canvas
# from reportlab.lib.utils import ImageReader
# from collections import namedtuple
# 
# MAX_WEEKLY_KAZANIM = 6
# OUTPUT_DIR = "output_plans"
# HISTORY_FILE = "kazanım_history.json"
# Kazanım = namedtuple("Kazanım", ["ders", "kazanım", "yüzde"])
# 
# def load_history():
#     if os.path.exists(HISTORY_FILE):
#         with open(HISTORY_FILE, "r", encoding="utf-8") as f:
#             return json.load(f)
#     return {}
# 
# def save_history(data):
#     with open(HISTORY_FILE, "w", encoding="utf-8") as f:
#         json.dump(data, f, ensure_ascii=False, indent=2)
# 
# def parse_pdf(pdf_bytes):
#     students = []
#     with pdfplumber.open(pdf_bytes) as pdf:
#         for page in pdf.pages:
#             text = page.extract_text()
#             if not text:
#                 continue
#             lines = [l.strip() for l in text.split("\\n") if l.strip()]
#             name_line = lines[0]
#             if "(" in name_line and ")" in name_line:
#                 student_name = name_line.split("(")[0].strip()
#                 student_class = name_line.split("(")[1].replace(")", "").strip()
#             else:
#                 student_name = name_line.strip()
#                 student_class = "Bilinmiyor"
#             kazanımlar = []
#             for line in lines[1:]:
#                 if "%" in line:
#                     try:
#                         ders = ""
#                         if line.lower().startswith("matematik"):
#                             ders = "Matematik"
#                         elif line.lower().startswith("türkçe"):
#                             ders = "Türkçe"
#                         elif line.lower().startswith("fen"):
#                             ders = "Fen Bilimleri"
#                         elif line.lower().startswith("sosyal"):
#                             ders = "Sosyal Bilgiler"
#                         else:
#                             continue
#                         parts = line.split("%")
#                         yuzde = int(parts[-1].strip())
#                         kazanım_text = parts[0].split(ders)[-1].strip()
#                         kazanımlar.append({"ders": ders, "kazanım": kazanım_text, "yüzde": yuzde})
#                     except Exception:
#                         continue
#             students.append({"isim": student_name, "sınıf": student_class, "kazanımlar": kazanımlar})
#     return students
# 
# def get_activity_text(yuzde, second_time=False):
#     if yuzde <= 50:
#         if second_time:
#             return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru)"
#         return "Vitamin online platformundan konu tekrarı videoları izle. Platformdaki etkinlikleri tamamla."
#     if 51 <= yuzde <= 70:
#         return "Vitamin online platformundaki konu tekrarı videolarını izle. Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Hatalı sorularını defterine yaz."
#     if 71 <= yuzde <= 85:
#         return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Yeni nesil 5 soru çöz. Hatalı sorularını defterine yaz."
#     if 86 <= yuzde <= 99:
#         return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Yeni nesil 5 soru çöz. Hatalı sorularını defterine yaz."
#     if yuzde == 100:
#         return "Kendi belirleyeceğin konu ile ilgili 1 test çöz. Ardından yeni nesil 5 soru çöz."
#     return ""
# 
# def build_plan(kazanımlar, student_id, history):
#     today = datetime.date.today()
#     student_hist = history.get(student_id, {})
#     plan_slots = {"Pazartesi": [], "Salı": [], "Çarşamba": [], "Perşembe": []}
#     kazanımlar.sort(key=lambda x: x["yüzde"])
#     math_count = turkce_count = fen_count = sosyal_count = total = 0
#     for k in kazanımlar:
#         if total >= MAX_WEEKLY_KAZANIM:
#             break
#         d = k["ders"].lower()
#         if "matematik" in d:
#             if math_count < 2:
#                 if len(plan_slots["Pazartesi"]) < 1:
#                     plan_slots["Pazartesi"].append(k)
#                 elif len(plan_slots["Perşembe"]) < 1:
#                     plan_slots["Perşembe"].append(k)
#                 math_count += 1
#                 total += 1
#         elif "türkçe" in d:
#             if turkce_count < 2 and len(plan_slots["Salı"]) < 2:
#                 plan_slots["Salı"].append(k)
#                 turkce_count += 1
#                 total += 1
#         elif "fen" in d:
#             if fen_count < 2 and len(plan_slots["Çarşamba"]) < 2:
#                 plan_slots["Çarşamba"].append(k)
#                 fen_count += 1
#                 total += 1
#         elif "sosyal" in d:
#             if sosyal_count < 2 and len(plan_slots["Çarşamba"]) < 2:
#                 plan_slots["Çarşamba"].append(k)
#                 sosyal_count += 1
#                 total += 1
#     plan_list = []
#     for day in ["Pazartesi", "Salı", "Çarşamba", "Perşembe"]:
#         for e in plan_slots[day]:
#             second_time = e["kazanım"] in student_hist
#             activity = get_activity_text(e["yüzde"], second_time)
#             plan_list.append({"gün": day, "ders": e["ders"], "kazanım": e["kazanım"], "yüzde": e["yüzde"], "etkinlik": activity})
#     plan_list.append({"gün": "Cuma", "ders": "Tüm Dersler", "kazanım": "Hafta boyunca çalıştığın tüm kazanımlar", "yüzde": "-", "etkinlik": "Hafta boyunca çalıştığın tüm kazanımlardan 2’şer yeni nesil soru çöz."})
#     today_str = today.isoformat()
#     for p in plan_list:
#         if p["kazanım"]:
#             student_hist[p["kazanım"]] = today_str
#     history[student_id] = student_hist
#     return plan_list, history
# 
# def create_pdf(student_name, student_class, plan_list, logo_path=None):
#     os.makedirs(OUTPUT_DIR, exist_ok=True)
#     filename = f"{OUTPUT_DIR}/{student_name.replace(' ', '_')}_{student_class.replace('/', '')}_Plan.pdf"
#     c = canvas.Canvas(filename, pagesize=A4)
#     width, height = A4
#     if logo_path:
#         try:
#             logo = ImageReader(logo_path)
#             c.drawImage(logo, 25 * mm, height - 35 * mm, width=25 * mm, height=25 * mm, mask='auto')
#         except Exception:
#             pass
#     c.setFont("Helvetica-Bold", 16)
#     c.drawCentredString(width / 2, height - 30 * mm, f"{student_name} ({student_class}) – 1. Haftalık Çalışma Planı (Güncel)")
#     c.line(20 * mm, height - 35 * mm, width - 20 * mm, height - 35 * mm)
#     start_y = height - 45 * mm
#     headers = ["Gün", "Ders", "Kazanım", "Başarı %", "Çalışma Türü"]
#     x_pos = [20 * mm, 45 * mm, 85 * mm, 145 * mm, 170 * mm]
#     c.setFont("Helvetica-Bold", 9)
#     for i, h in enumerate(headers):
#         c.drawString(x_pos[i], start_y, h)
#     y = start_y - 8 * mm
#     line_height = 8 * mm
#     c.setFont("Helvetica", 9)
#     for item in plan_list:
#         if y < 25 * mm:
#             c.showPage()
#             y = height - 30 * mm
#         c.drawString(x_pos[0], y, item["gün"])
#         c.drawString(x_pos[1], y, item["ders"])
#         c.drawString(x_pos[2], y, item["kazanım"])
#         c.drawString(x_pos[3], y, str(item["yüzde"]))
#         text = c.beginText(x_pos[4], y)
#         text.setFont("Helvetica", 8)
#         desc = item["etkinlik"]
#         while len(desc) > 45:
#             cut = desc[:45]
#             last_space = cut.rfind(" ")
#             if last_space != -1:
#                 cut = desc[:last_space]
#                 desc = desc[last_space + 1:]
#             else:
#                 desc = desc[45:]
#             text.textLine(cut)
#         text.textLine(desc)
#         c.drawText(text)
#         y -= line_height
#     c.save()
#     return filename
# 
# st.set_page_config(page_title="Haftalık Çalışma Planı", page_icon="📘", layout="wide")
# st.title("📘 Haftalık Kazanım Takip ve Çalışma Planı Oluşturucu")
# 
# logo_file = st.file_uploader("Okul logosunu yükleyin (isteğe bağlı)", type=["png", "jpg", "jpeg"])
# uploaded_file = st.file_uploader("Sınav Sonuç PDF Dosyasını Yükleyin", type=["pdf"])
# 
# if uploaded_file:
#     with st.spinner("PDF analiz ediliyor..."):
#         students = parse_pdf(uploaded_file)
#         history = load_history()
#         outputs = []
#         for s in students:
#             if not s["kazanımlar"]:
#                 continue
#             student_id = f"{s['isim'].replace(' ', '_')}_{s['sınıf']}"
#             plan_list, history = build_plan(s["kazanımlar"], student_id, history)
#             logo_path = BytesIO(logo_file.read()) if logo_file else None
#             pdf_path = create_pdf(s["isim"], s["sınıf"], plan_list, logo_path)
#             outputs.append(pdf_path)
#         save_history(history)
#     st.success(f"🎯 {len(outputs)} öğrenci için plan oluşturuldu!")
#     student_names = [os.path.basename(out).replace("_Plan.pdf", "").replace("_", " ") for out in outputs]
#     search_query = st.text_input("🔍 Bir öğrenci arayın (örneğin 'Demir', '4A'):")
#     filtered_outputs = [(n, o) for n, o in zip(student_names, outputs) if search_query.strip().lower() in n.lower()] or list(zip(student_names, outputs))
#     for name, out in filtered_outputs:
#         with open(out, "rb") as f:
#             st.download_button(f"📄 {name} - Planı indir", f, file_name=os.path.basename(out), mime="application/pdf")
#     zip_buffer = BytesIO()
#     with zipfile.ZipFile(zip_buffer, "w") as zipf:
#         for fpath in outputs:
#             zipf.write(fpath, os.path.basename(fpath))
#     zip_buffer.seek(0)
#     st.download_button("📦 Tüm planları ZIP olarak indir", zip_buffer, file_name="Tum_Planlar.zip", mime="application/zip")
#

from pyngrok import ngrok

ngrok.kill()  # varsa eski tünelleri kapat
ngrok.set_auth_token("35BXqu4dzYd1y926ldjyHLFlnT1_2TqswTgS8cwoGkiZUVecg")
public_url = ngrok.connect(addr='8501', proto='http')
print(f"Streamlit App URL: {public_url}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vibe_planner_app.py
# # 📘 Orkun Temeltaş - Haftalık Çalışma Planı Arayüzü (Colab uyumlu)
# # Tam işlevli sürüm (arama, logo, ZIP, çoklu öğrenci destekli)
# 
# import streamlit as st
# import os
# import pdfplumber
# import datetime
# import json
# import zipfile
# from io import BytesIO
# from reportlab.lib.pagesizes import A4
# from reportlab.lib.units import mm
# from reportlab.pdfgen import canvas
# from reportlab.lib.utils import ImageReader
# from collections import namedtuple
# 
# MAX_WEEKLY_KAZANIM = 6
# OUTPUT_DIR = "output_plans"
# HISTORY_FILE = "kazanım_history.json"
# Kazanım = namedtuple("Kazanım", ["ders", "kazanım", "yüzde"])
# 
# def load_history():
#     if os.path.exists(HISTORY_FILE):
#         with open(HISTORY_FILE, "r", encoding="utf-8") as f:
#             return json.load(f)
#     return {}
# 
# def save_history(data):
#     with open(HISTORY_FILE, "w", encoding="utf-8") as f:
#         json.dump(data, f, ensure_ascii=False, indent=2)
# 
# def parse_pdf(pdf_bytes):
#     students = []
#     with pdfplumber.open(pdf_bytes) as pdf:
#         for page in pdf.pages:
#             text = page.extract_text()
#             if not text:
#                 continue
#             lines = [l.strip() for l in text.split("\\n") if l.strip()]
#             name_line = lines[0]
#             if "(" in name_line and ")" in name_line:
#                 student_name = name_line.split("(")[0].strip()
#                 student_class = name_line.split("(")[1].replace(")", "").strip()
#             else:
#                 student_name = name_line.strip()
#                 student_class = "Bilinmiyor"
#             kazanımlar = []
#             for line in lines[1:]:
#                 if "%" in line:
#                     try:
#                         ders = ""
#                         if line.lower().startswith("matematik"):
#                             ders = "Matematik"
#                         elif line.lower().startswith("türkçe"):
#                             ders = "Türkçe"
#                         elif line.lower().startswith("fen"):
#                             ders = "Fen Bilimleri"
#                         elif line.lower().startswith("sosyal"):
#                             ders = "Sosyal Bilgiler"
#                         else:
#                             continue
#                         parts = line.split("%")
#                         yuzde = int(parts[-1].strip())
#                         kazanım_text = parts[0].split(ders)[-1].strip()
#                         kazanımlar.append({"ders": ders, "kazanım": kazanım_text, "yüzde": yuzde})
#                     except Exception:
#                         continue
#             students.append({"isim": student_name, "sınıf": student_class, "kazanımlar": kazanımlar})
#     return students
# 
# def get_activity_text(yuzde, second_time=False):
#     if yuzde <= 50:
#         if second_time:
#             return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru)"
#         return "Vitamin online platformundan konu tekrarı videoları izle. Platformdaki etkinlikleri tamamla."
#     if 51 <= yuzde <= 70:
#         return "Vitamin online platformundaki konu tekrarı videolarını izle. Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Hatalı sorularını defterine yaz."
#     if 71 <= yuzde <= 85:
#         return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Yeni nesil 5 soru çöz. Hatalı sorularını defterine yaz."
#     if 86 <= yuzde <= 99:
#         return "Ek kaynaklarındaki ilgili kazanım/konu ile ilgili bir test çöz. (10 Soru). Yeni nesil 5 soru çöz. Hatalı sorularını defterine yaz."
#     if yuzde == 100:
#         return "Kendi belirleyeceğin konu ile ilgili 1 test çöz. Ardından yeni nesil 5 soru çöz."
#     return ""
# 
# def build_plan(kazanımlar, student_id, history):
#     today = datetime.date.today()
#     student_hist = history.get(student_id, {})
#     plan_slots = {"Pazartesi": [], "Salı": [], "Çarşamba": [], "Perşembe": []}
#     kazanımlar.sort(key=lambda x: x["yüzde"])
#     math_count = turkce_count = fen_count = sosyal_count = total = 0
#     for k in kazanımlar:
#         if total >= MAX_WEEKLY_KAZANIM:
#             break
#         d = k["ders"].lower()
#         if "matematik" in d:
#             if math_count < 2:
#                 if len(plan_slots["Pazartesi"]) < 1:
#                     plan_slots["Pazartesi"].append(k)
#                 elif len(plan_slots["Perşembe"]) < 1:
#                     plan_slots["Perşembe"].append(k)
#                 math_count += 1
#                 total += 1
#         elif "türkçe" in d:
#             if turkce_count < 2 and len(plan_slots["Salı"]) < 2:
#                 plan_slots["Salı"].append(k)
#                 turkce_count += 1
#                 total += 1
#         elif "fen" in d:
#             if fen_count < 2 and len(plan_slots["Çarşamba"]) < 2:
#                 plan_slots["Çarşamba"].append(k)
#                 fen_count += 1
#                 total += 1
#         elif "sosyal" in d:
#             if sosyal_count < 2 and len(plan_slots["Çarşamba"]) < 2:
#                 plan_slots["Çarşamba"].append(k)
#                 sosyal_count += 1
#                 total += 1
#     plan_list = []
#     for day in ["Pazartesi", "Salı", "Çarşamba", "Perşembe"]:
#         for e in plan_slots[day]:
#             second_time = e["kazanım"] in student_hist
#             activity = get_activity_text(e["yüzde"], second_time)
#             plan_list.append({"gün": day, "ders": e["ders"], "kazanım": e["kazanım"], "yüzde": e["yüzde"], "etkinlik": activity})
#     plan_list.append({"gün": "Cuma", "ders": "Tüm Dersler", "kazanım": "Hafta boyunca çalıştığın tüm kazanımlar", "yüzde": "-", "etkinlik": "Hafta boyunca çalıştığın tüm kazanımlardan 2’şer yeni nesil soru çöz."})
#     today_str = today.isoformat()
#     for p in plan_list:
#         if p["kazanım"]:
#             student_hist[p["kazanım"]] = today_str
#     history[student_id] = student_hist
#     return plan_list, history
# 
# def create_pdf(student_name, student_class, plan_list, logo_path=None):
#     os.makedirs(OUTPUT_DIR, exist_ok=True)
#     filename = f"{OUTPUT_DIR}/{student_name.replace(' ', '_')}_{student_class.replace('/', '')}_Plan.pdf"
#     c = canvas.Canvas(filename, pagesize=A4)
#     width, height = A4
#     if logo_path:
#         try:
#             logo = ImageReader(logo_path)
#             c.drawImage(logo, 25 * mm, height - 35 * mm, width=25 * mm, height=25 * mm, mask='auto')
#         except Exception:
#             pass
#     c.setFont("Helvetica-Bold", 16)
#     c.drawCentredString(width / 2, height - 30 * mm, f"{student_name} ({student_class}) – 1. Haftalık Çalışma Planı (Güncel)")
#     c.line(20 * mm, height - 35 * mm, width - 20 * mm, height - 35 * mm)
#     start_y = height - 45 * mm
#     headers = ["Gün", "Ders", "Kazanım", "Başarı %", "Çalışma Türü"]
#     x_pos = [20 * mm, 45 * mm, 85 * mm, 145 * mm, 170 * mm]
#     c.setFont("Helvetica-Bold", 9)
#     for i, h in enumerate(headers):
#         c.drawString(x_pos[i], start_y, h)
#     y = start_y - 8 * mm
#     line_height = 8 * mm
#     c.setFont("Helvetica", 9)
#     for item in plan_list:
#         if y < 25 * mm:
#             c.showPage()
#             y = height - 30 * mm
#         c.drawString(x_pos[0], y, item["gün"])
#         c.drawString(x_pos[1], y, item["ders"])
#         c.drawString(x_pos[2], y, item["kazanım"])
#         c.drawString(x_pos[3], y, str(item["yüzde"]))
#         text = c.beginText(x_pos[4], y)
#         text.setFont("Helvetica", 8)
#         desc = item["etkinlik"]
#         while len(desc) > 45:
#             cut = desc[:45]
#             last_space = cut.rfind(" ")
#             if last_space != -1:
#                 cut = desc[:last_space]
#                 desc = desc[last_space + 1:]
#             else:
#                 desc = desc[45:]
#             text.textLine(cut)
#         text.textLine(desc)
#         c.drawText(text)
#         y -= line_height
#     c.save()
#     return filename
# 
# st.set_page_config(page_title="Haftalık Çalışma Planı", page_icon="📘", layout="wide")
# st.title("📘 Haftalık Kazanım Takip ve Çalışma Planı Oluşturucu")
# 
# logo_file = st.file_uploader("Okul logosunu yükleyin (isteğe bağlı)", type=["png", "jpg", "jpeg"])
# uploaded_file = st.file_uploader("Sınav Sonuç PDF Dosyasını Yükleyin", type=["pdf"])
# 
# if uploaded_file:
#     with st.spinner("PDF analiz ediliyor..."):
#         students = parse_pdf(uploaded_file)
#         history = load_history()
#         outputs = []
#         for s in students:
#             if not s["kazanımlar"]:
#                 continue
#             student_id = f"{s['isim'].replace(' ', '_')}_{s['s['sınıf']}"
#             plan_list, history = build_plan(s["kazanımlar"], student_id, history)
#             logo_path = BytesIO(logo_file.read()) if logo_file else None
#             pdf_path = create_pdf(s["isim"], s["sınıf"], plan_list, logo_path)
#             outputs.append(pdf_path)
#         save_history(history)
#     st.success(f"🎯 {len(outputs)} öğrenci için plan oluşturuldu!")
#     student_names = [os.path.basename(out).replace("_Plan.pdf", "").replace("_", " ") for out in outputs]
#     search_query = st.text_input("🔍 Bir öğrenci arayın (örneğin 'Demir', '4A'):")
#     filtered_outputs = [(n, o) for n, o in zip(student_names, outputs) if search_query.strip().lower() in n.lower()] or list(zip(student_names, outputs))
#     for name, out in filtered_outputs:
#         with open(out, "rb") as f:
#             st.download_button(f"📄 {name} - Planı indir", f, file_name=os.path.basename(out), mime="application/pdf")
#     zip_buffer = BytesIO()
#     with zipfile.ZipFile(zip_buffer, "w") as zipf:
#         for fpath in outputs:
#             zipf.write(fpath, os.path.basename(fpath))
#     zip_buffer.seek(0)
#     st.download_button("📦 Tüm planları ZIP olarak indir", zip_buffer, file_name="Tum_Planlar.zip", mime="application/zip")

!nohup streamlit run vibe_planner_app.py --server.port 8501 &>/dev/null&